let DateGenerator = require('random-date-generator');



const gender = ["1","2","3"]
const countries = [
    "AF",
    "AX",
    "AL",
    "DZ",
    "AS",
    "AD",
    "AO",
    "AI",
    "AQ",
    "AG",
    "AR",
    "AM",
    "AW",
    "AU",
    "AT",
    "AZ",
    "BS",
    "BH",
    "BD",
    "BB",
    "BY",
    "BE",
    "BZ",
    "BJ",
    "BM",
    "BT",
    "BO",
    "BQ",
    "BA",
    "BW",
    "BV",
    "BR",
    "IO",
    "BN",
    "BG",
    "BF",
    "BI",
    "KH",
    "CM",
    "CA",
    "CV",
    "KY",
    "CF",
    "TD",
    "CL",
    "CN",
    "CX",
    "CC",
    "CO",
    "KM",
    "CG",
    "CD",
    "CK",
    "CR",
    "CI",
    "HR",
    "CU",
    "CW",
    "CY",
    "CZ",
    "DK",
    "DJ",
    "DM",
    "DO",
    "EC",
    "EG",
    "SV",
    "GQ",
    "ER",
    "EE",
    "ET",
    "FK",
    "FO",
    "FJ",
    "FI",
    "FR",
    "GF",
    "PF",
    "TF",
    "GA",
    "GM",
    "GE",
    "DE",
    "GH",
    "GI",
    "GR",
    "GL",
    "GD",
    "GP",
    "GU",
    "GT",
    "GG",
    "GN",
    "GW",
    "GY",
    "HT",
    "HM",
    "VA",
    "HN",
    "HK",
    "HU",
    "IS",
    "IN",
    "ID",
    "IR",
    "IQ",
    "IE",
    "IM",
    "IL",
    "IT",
    "JM",
    "JP",
    "JE",
    "JO",
    "KZ",
    "KE",
    "KI",
    "KP",
    "KR",
    "XK",
    "KW",
    "KG",
    "LA",
    "LV",
    "LB",
    "LS",
    "LR",
    "LY",
    "LI",
    "LT",
    "LU",
    "MO",
    "MK",
    "MG",
    "MW",
    "MY",
    "MV",
    "ML",
    "MT",
    "MH",
    "MQ",
    "MR",
    "MU",
    "YT",
    "MX",
    "FM",
    "MD",
    "MC",
    "MN",
    "ME",
    "MS",
    "MA",
    "MZ",
    "MM",
    "NA",
    "NR",
    "NP",
    "NL",
    "AN",
    "NC",
    "NZ",
    "NI",
    "NE",
    "NG",
    "NU",
    "NF",
    "MP",
    "NO",
    "OM",
    "PK",
    "PW",
    "PS",
    "PA",
    "PG",
    "PY",
    "PE",
    "PH",
    "PN",
    "PL",
    "PT",
    "PR",
    "QA",
    "RE",
    "RO",
    "RU",
    "RW",
    "BL",
    "SH",
    "KN",
    "LC",
    "MF",
    "PM",
    "VC",
    "WS",
    "SM",
    "ST",
    "SA",
    "SN",
    "RS",
    "CS",
    "SC",
    "SL",
    "SG",
    "SX",
    "SK",
    "SI",
    "SB",
    "SO",
    "ZA",
    "GS",
    "SS",
    "ES",
    "LK",
    "SD",
    "SR",
    "SJ",
    "SZ",
    "SE",
    "CH",
    "SY",
    "TW",
    "TJ",
    "TZ",
    "TH",
    "TL",
    "TG",
    "TK",
    "TO",
    "TT",
    "TN",
    "TR",
    "TM",
    "TC",
    "TV",
    "UG",
    "UA",
    "AE",
    "GB",
    "US",
    "UM",
    "UY",
    "UZ",
    "VU",
    "VE",
    "VN",
    "VG",
    "VI",
    "WF",
    "EH",
    "YE",
    "ZM",
    "ZW"
];
const device_name= ["iPhone 11 Pro Max",
"iPhone 12 Pro",
"iPhone 12 Mini",
"iPhone 12 Pro Max",
"iPhone 14",
"iPhone 13 Pro",
"iPhone 13",
"iPhone XR",
"iPhone XS",
"iPhone 11",
"iPhone 11 Pro",
"iPhone 8",
"iPhone 13 Mini",
"iPhone 13 Pro Max",
"iPhone 13 Pro",
"iPhone 13",
"iPhone XS",
"iPhone 11",
"iPhone 11 Pro Max",
"iPhone 12 Pro",
"iPhone 12",
"iPhone 12 Mini",
"iPhone 12 Pro Max",
"iPhone SE 2020",
"iPhone 8",
"iPhone XS",
"iPhone 11",
"iPhone 11 Pro",
"iPhone 11 Pro Max",
"iPhone 8 Plus",
"iPhone 6S",
"iPhone 7",
"iPhone 8",
"iPhone XS Max",
"iPhone XS",
"iPhone XR",
"iPhone 6",
"iPhone 6S",
"iPhone 6S Plus",
"iPhone SE",
"iPhone 8",
"iPhone 8 Plus",
"iPhone X",
"iPhone 7",
"iPhone 6S Plus",
"iPhone 6S",
"iPhone 6 Plus",
"iPhone 6",
"iPad",
"iPad 8th",
"iPad Pro ",
"iPad 5th",
"iPad Air 5",
"iPad Mini ",
"iPad Pro ",
"iPad 9th",
"iPad 8th",
"iPad Air 4",
"iPad Pro ",
"iPad Pro ",
"iPad Pro ",
"iPad 7",
"iPad Air ",
"iPad Mini ",
"iPad Pro 11 ",
"iPad Pro ",
"iPad Pro ",
"iPad Air ",
"iPad Mini ",
"iPad Pro ",
"iPad Pro ",
"iPad 6th",
"iPad 5th",
"iPad Mini 4",
"iPad Pro ",
"iPad Pro ",
"iPad Air 2",
"iPad Mini",
"Galaxy S22+", "Galaxy S22 Ultra", "Galaxy 521", "Galaxy S21", "Galaxy 521+", "Galaxy S21 Ultra", "Galaxy S20", "Galaxy A52", "Galaxy M32 Galaxy M52", "Galaxy S20", "Galaxy $20+", "Galaxy S20 Ultra", "Galaxy A51", "Galaxy A11", "Galaxy Note 20 Ultra", "Galaxy Note 20", "Galaxy S10e", "Galaxy S10", "Galaxy S10+", "Galaxy S9+", "Galaxy A10", "Galaxy Note 10 Galaxy Note 10+", "Galaxy Note 9 Galaxy 59", "Galaxy S9+ Galaxy J7 Prime", "Galaxy AB", "Galaxy Note 8", "Galaxy S8", "Galaxy S5", "Galaxy Tab 58", "Galaxy Tab S7", "Galaxy Tab S5e", "Galaxy Tab S6"]
var randomGender = gender[Math.floor(Math.random()*gender.length)]


var randomCountries = countries[Math.floor(Math.random()*countries.length)]


var randomDevice_name = device_name[Math.floor(Math.random()*device_name.length)]

// DateGenerator.getRandomDate(); // random date

// let startDate = new Date(1950, 2, 2);
// let endDate = new Date(2007, 3, 3);
// let newdate = DateGenerator.getRandomDateInRange(startDate, endDate);
// console.log(DateGenerator.getRandomDateInRange(startDate, endDate));
// console.log(DateGenerator.getRandomDateInRange(startDate, endDate));
// console.log(DateGenerator.getRandomDateInRange(startDate, endDate));

module.exports = {gender,countries,device_name};

